# Generated by Django 5.1.3 on 2024-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Othello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='black', max_length=5)),
                ('winner', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
