# Generated by Django 5.1.4 on 2025-01-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Othello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('black_score', models.IntegerField(default=0)),
                ('white_score', models.IntegerField(default=0)),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='black', max_length=5)),
                ('winner', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placeable_positions', models.JSONField(default=list)),
                ('player_black', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('player_white', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
