# Generated by Django 5.1.4 on 2025-01-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='othello',
            name='player_black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='othello',
            name='player_white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='othello',
            name='room_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='othello',
            name='winner',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('draw', 'Draw')], max_length=5, null=True),
        ),
        migrations.AddIndex(
            model_name='othello',
            index=models.Index(fields=['room_name'], name='game_othell_room_na_d8a3f1_idx'),
        ),
    ]
