# Generated by Django 5.1.4 on 2025-01-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='othello',
            name='placeable_positions',
            field=models.JSONField(default=list),
        ),
    ]
