# Generated by Django 5.1.4 on 2025-01-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_othello_placeable_positions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='othello',
            name='black_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='othello',
            name='player_black',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othello',
            name='player_white',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othello',
            name='white_score',
            field=models.IntegerField(default=0),
        ),
    ]
